Task1

In [1]:
import numpy as np

In [2]:
m = np.array([i for i in range(12,24)])

In [3]:
m

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
m1 = m.reshape(6,2)

In [5]:
m2 = m.reshape(2,6)

In [6]:
m3 = m.reshape(3,4)

In [7]:
m4 = m.reshape(4,3)

In [9]:
m5 = m.reshape(12,1)

In [10]:
m6 = m.reshape(12,-1)

In [11]:
m7 = m.reshape(6,-1)

In [13]:
m8 = m.reshape(-1,4)

In [14]:
m9 = m.reshape(-1,3)

In [15]:
m10 = m.reshape(-1,2)

In [16]:
mnorm = np.array([[np.random.normal(0,1.0, 4)],
                 [np.random.normal(0,1.0, 4)],
                 [np.random.normal(0,1.0, 4)]])

In [17]:
np.reshape(mnorm, (1,12))

array([[ 0.34925207, -0.797771  ,  0.90923068, -1.64061647, -1.22531123,
         0.21467558,  1.04406093, -0.57672242, -0.0292571 , -0.49362023,
        -0.07334734,  0.44564029]])

In [18]:
c = np.array ([i for i in range(20,0,-2)])

In [24]:
b = np.ravel(c)

In [25]:
c

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [26]:
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [27]:
np.shape(b)

(10,)

In [28]:
np.shape(c)

(10,)

In [1]:
import numpy as np

In [3]:
a = np.array([i for i in range(0,12)])


In [4]:
a = a.reshape(4,3)

In [6]:
at = a.transpose()

In [7]:
at

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [8]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
b = np.dot(a,at)

In [10]:
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [11]:
np.linalg.inv(b)

LinAlgError: Singular matrix

In [14]:
np.linalg.det(b)

0.0

In [15]:
a = np.array(np.random.randint(0,16,16))

In [16]:
c = a.reshape(4,4)

In [17]:
c

array([[ 1,  2,  6,  8],
       [ 0,  3, 14, 14],
       [ 5, 14,  3, 15],
       [13, 12,  1, 11]])

In [20]:
d = b + c * 10

In [21]:
d

array([[ 15,  34,  83, 112],
       [ 14,  80, 226, 262],
       [ 73, 226, 179, 362],
       [162, 242, 222, 412]])

In [22]:
np.linalg.det(d)

36198599.999999896

In [23]:
np.linalg.matrix_rank(d)

4

In [24]:
np.linalg.inv(d)

array([[ 0.00059837, -0.00236307, -0.01163857,  0.01156619],
       [-0.08321427,  0.02318322,  0.00508638,  0.00340952],
       [-0.0718619 ,  0.02950446, -0.00778317,  0.00761134],
       [ 0.0873647 , -0.02858619,  0.00578254, -0.00822463]])

In [25]:
dinv = np.linalg.inv(d)

In [26]:
dinv[dinv > 0] = 1

In [27]:
dinv[dinv <= 0] = 0

In [28]:
dinv

array([[1., 0., 0., 1.],
       [0., 1., 1., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [29]:
e = np.where(dinv == 0, d,c)

In [30]:
e

array([[  1,  34,  83,   8],
       [ 14,   3,  14,  14],
       [ 73,  14, 179,  15],
       [ 13, 242,   1, 412]])

TASK2


In [32]:
m = np.array([[ 1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])

In [33]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [36]:
mean_a = np.mean(m,1)

In [37]:
mean_a

array([2. , 8.4])

In [38]:
mean_a = mean_a.reshape(2,1)

In [39]:
a_centered = m - mean_a

In [40]:
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])